project_name: biasing_entity
train_data:
  dataset_name: cached
  cache_path: az://${DATA_STORAGE}/data/boren/data/cache_datasets/hcv2_fy22_info_tag/
  num_proc: "auto"
  pre_process:
    # num_egs: 300000
    path_map:
      field: audio_chunk
      src_part: "az://orngwus2cresco/"
      dst_part: "az://${DATA_STORAGE}/"
  filter_by_keywords:
    min_num: 1
  add_prompt:
    task: rare_asr
    forced: True
reward_funcs: [reward_full_error, reward_bias_error]
reward_func_kwargs:
  tn: simple
  unit: char
reward_weights: [1, 5]
# reward_funcs: [reward_unbias_accuracy, reward_bias_accuracy]
# scale_rewards: True
# model_name_or_path: /root/data/ckp/hf_models/phi4_mm_bias
model_name_or_path: /root/data/ckp/hf_models/Phi-4-multimodal-instruct
# model_name_or_path: /root/data/ckp/hf_models/phi-libri_ft_m1000_p8_new-QpHq/5000_hf
# model_name_or_path: /datablob1/users/boren/data/hf_models/phi-libri_ft_m1000_p8_new-QpHq_v1
report_to: [wandb]
# num_train_epochs: 1
max_samples: 300000
learning_rate: 1e-5
# new_lora: True
lr_scheduler_type: cosine #cosine
temperature: 0.6
output_dir: ./output
per_device_train_batch_samples: 8
num_generations: 4
# generation_scale: 2
inject_reference: True
# token_entropy_percentile_threshold: 0.8
# steps_per_generation: 2 # generate 4 batches
gradient_accumulation_steps: 4
logging_steps: 10
bf16: True
gradient_checkpointing: True
log_completions: True
max_prompt_length: 6000
max_completion_length: 512
wandb_log_unique_prompts: True
# beta: 0.1
epsilon_high: 0.28
save_only_model: True
save_total_limit: 5
save_on_each_node: True
save_steps: 100
use_vllm: True
vllm_mode: colocate
vllm_tensor_parallel_size: 1
vllm_gpu_memory_utilization: 0.35
vllm_imp_ratio_cap: 5
# vllm_server_host: ${VLLM_SERVER_HOST} # dev-n1-wus2-0
# vllm_server_port: 26500

eval_strategy: steps
eval_on_start: False
eval_steps: 200
per_device_eval_batch_size: 200
num_eval_generations: 2
eval_data:
  - nickname: clean_no
    dataset_name: ls_bias
    jsonl_path: /root/data/librispeech_biasing/ref/test-clean.biasing_100.jsonl
    tag: ""
    data_dir: az://${DATA_STORAGE}/data/boren/data
  - nickname: other_no
    dataset_name: ls_bias
    jsonl_path: /root/data/librispeech_biasing/ref/test-other.biasing_100.jsonl
    tag: ""
    data_dir: az://${DATA_STORAGE}/data/boren/data
  - nickname: entity_Gaming_0
    dataset_name: inhouse_entity
    data_dir: az://${DATA_STORAGE}/data/boren/data/
    src_dir: /home/boren/data/
    jsonl_path: az://${DATA_STORAGE}/data/boren/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Gaming_Entity_FY24Q1_en-US_DTEST/segments.jsonl
    distractor_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 0
  - nickname: entity_Insurance_0
    dataset_name: inhouse_entity
    data_dir: az://${DATA_STORAGE}/data/boren/data/
    src_dir: /home/boren/data/
    jsonl_path: az://${DATA_STORAGE}/data/boren/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Insurance_Entity_FY24Q1_en-US_DTEST/segments.jsonl
    distractor_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 0
  - nickname: entity_K12HigherEdu_0
    dataset_name: inhouse_entity
    data_dir: az://${DATA_STORAGE}/data/boren/data/
    src_dir: /home/boren/data/
    jsonl_path: az://${DATA_STORAGE}/data/boren/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_K12HigherEdu_Entity_FY24Q4_en-US_DTEST_OfflineDataCollection/segments.jsonl
    distractor_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 0
  - nickname: entity_Retail_0
    dataset_name: inhouse_entity
    data_dir: az://${DATA_STORAGE}/data/boren/data/
    src_dir: /home/boren/data/
    jsonl_path: az://${DATA_STORAGE}/data/boren/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Retail_Entity_FY24Q4_en-US_DTEST_OfflineDataCollection/segments.jsonl
    distractor_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 0
  - nickname: entity_ScienceTech_0
    dataset_name: inhouse_entity
    data_dir: az://${DATA_STORAGE}/data/boren/data/
    src_dir: /home/boren/data/
    jsonl_path: az://${DATA_STORAGE}/data/boren/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_ScienceTech_Entity_FY24Q1_en-US_DTEST/segments.jsonl
    distractor_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 0
