# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
description: speech-training
target:
    service: sing
    name: cogs-sing-shared-eu
environment:
    # registry: florencecontainerregistryeu.azurecr.io
    # image: haiping/h100-nvidia23.10-pytorch2.1.1-cuda12.2.2-deepspeed0.12.3-flashattn2.3.4:20231124
    # username: FlorenceContainerRegistryEU
    registry: sramdevregistry.azurecr.io
    image: jing-dev:a100_latest
    username: sramdevregistry

    setup:
        - set -e -o xtrace
        - pip install -e .
        - wget https://aka.ms/downloadazcopy-v10-linux && tar xzf downloadazcopy-v10-linux
        - sudo mv azcopy_linux_amd64_*/azcopy /usr/local/bin/azcopy
        - pip install azure-storage-blob==12.19.1
        - pip install -U transformers==4.46.1
        - pip install --upgrade Pillow
        - pip install webp
        - pip install openai-whisper
        - pip install typing_extensions==4.7.1
        - pip install pydantic==2.0.3
        - pip install backoff
        - pip install unidecode
        - pip install timm
        - pip install mup fire

storage:
    output:
        storage_account_name: tsstd01uks
        container_name: data
    data_blob:
        container_name: data
        mount_dir: /datablob1
        storage_account_name: highperf01eus

code:
    local_dir: ./
jobs:
    - name: phi-omni-sqa-zh
      #   sku: 1x32G8-V100-IB-NvLink@eastus
      sku: 1xND40rs_v2@eastus
      sla_tier: basic
      priority: high
      mpi: True
      process_count_per_node: 8
      command:
          - ls -hl
          - pwd
          - python scripts/train/allreduce_test.py
          - cd scripts/train
          - ls -hl
          - export NCCL_P2P_LEVEL=NVL
          #   - python fake.py
          - python ds_train_advanced.py configs/phi3_audio/cascade_encoder_stage2/phiS-sqa-zh.yaml --output_dir $$AMLT_OUTPUT_DIR

      submit_args:
          container_args:
              shm_size: 1024g
          env:
              NCCL_TOPO_FILE: "topology.xml"
              NCCL_DEBUG_SUBSYS: "INIT,GRAPH"
              NCCL_DEBUG: "INFO"
              _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/48b6cd5e-3ffe-4c2e-9e99-5760a42cd093/resourceGroups/cogsvc-sing/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cogsvc-sing-uai"

      identity: managed
