dataset_name: trl-lib/ultrafeedback_binarized
model_name_or_path: Qwen/Qwen2-0.5B-Instruct
learning_rate: 5.0e-6
num_train_epochs: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
gradient_checkpointing: True
logging_steps: 1
output_dir: output/Qwen2-0.5B-DPO
no_remove_unused_columns: True
use_peft: True
lora_r: 32
lora_alpha: 16