dataset_name: tsv
dataset_config:
    num_egs: 10000
    tsv_paths: /datablob1/users/ruchaofan/wavllm_data/wavllm/converted_path_train_data_4chunk/asr_train_transcribe.tsv
    biasing:
        bias_prob: 0.9
        hit_prob: 0.9
        max_piece_len: 1
        max_num: 300
    simu_perference:
        error_rate: 0.25
        buffer_size: 10000
model_name_or_path: microsoft/Phi-4-multimodal-instruct
# job_name: phi4_mm_bias_grpo
report_to: [wandb]
learning_rate: 5.0e-6
lr_scheduler_type: cosine
output_dir: ./output
num_train_epochs: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: True
logging_steps: 1
bf16: True
max_prompt_length: 1024
wandb_log_unique_prompts: True
# beta: 0.0
