dataset_name: tsv
dataset_config:
    num_egs: 20000
    tsv_paths: /datablob1/users/ruchaofan/wavllm_data/wavllm/converted_path_train_data_4chunk/asr_train_transcribe.tsv
    biasing:
        bias_prob: 0.9
        hit_prob: 0.5
        max_piece_len: 2
        max_num: 200
report_to: [wandb]
learning_rate: 5e-6
lr_scheduler_type: cosine
output_dir: ./output
per_device_train_batch_size: 32
num_generations: 16
logging_steps: 1
bf16: True
gradient_checkpointing: True
log_completions: True
max_prompt_length: 1024
max_completion_length: 256
wandb_log_unique_prompts: True
beta: 0.1
epsilon_high: 0.28
