dataset_name: openasr
dataset_config:
    num_egs: 100
    split: test.clean
    name: librispeech
    biasing:
        bias_prob: 1.0
        hit_prob: 0.9
        max_piece_len: 1
        max_num: 2
reward_funcs: [reward_bias_error, reward_word_error]
reward_weights: [2, 1]
model_name_or_path: /home/boren/phi4_mm_bias
job_name: grpo_bias_debug
report_to: [wandb]
learning_rate: 5e-6
lr_scheduler_type: cosine
output_dir: ./output/grpo_bias_debug
per_device_train_batch_size: 8
num_generations: 8
logging_steps: 1
bf16: True
gradient_checkpointing: True
log_completions: True
max_prompt_length: 1024
max_completion_length: 256
wandb_log_unique_prompts: True
save_steps: 5
# beta: 0.0
# epsilon_high: 0.28
