dataset_name: tsv
dataset_config:
    num_egs: 5000
    tsv_paths: /datablob1/users/ruchaofan/wavllm_data/wavllm/converted_path_train_data_4chunk/asr_train_transcribe_shuf.tsv
    biasing:
        buffer_size: 10000
        max_piece_len: 4
        max_num: 500
        bias_prob: 0.8
        hit_prob: 0.8
        log_interval: 1000 # print biasing every 10000 samples
        new_sampling: True

reward_funcs: [reward_word_error, reward_bias_error]
reward_weights: [1, 2]
# model_name_or_path: /uksblob/users/boren/data/hf_models/phi-libri_ft_m1000_p8_new-QpHq
model_name_or_path: /datablob1/users/boren/data/hf_models/phi-libri_ft_m1000_p8_new-QpHq_v1
# job_name: phi4_mm_bias_grpo
report_to: [wandb]
learning_rate: 5e-6
lr_scheduler_type: cosine
output_dir: ./output
per_device_train_batch_size: 24
num_generations: 12
logging_steps: 10
bf16: True
gradient_checkpointing: True
log_completions: True
max_prompt_length: 4096
max_completion_length: 512
wandb_log_unique_prompts: True
# beta: 0.1
epsilon_high: 0.28
save_steps: 100
