dataset_name: tsv
dataset_config:
    # num_egs: 12
    # tsv_paths: az://orngwus2cresco/data/boren/data/LibriSpeech/ls_30k_shuf.tsv
    tsv_paths: /root/data/LibriSpeech/debug.tsv
    biasing:
        bias_prob: 0.8
        hit_prob: 0.8
        max_piece_len: 1
        max_num: 100
reward_funcs: [reward_word_error, reward_bias_error]
reward_weights: [1, 1]
# model_name_or_path: az://orngwus2cresco/data/boren/data/ckp/phi4_mm_bias
model_name_or_path: /root/data/ckp/hf_models/phi4_mm_bias
# model_name_or_path: /root/data/ckp/hf_models/phi4_mm_bias
# job_name: phi4_mm_bias_grpo
report_to: [wandb]
learning_rate: 5e-6
lr_scheduler_type: cosine
output_dir: ./output
per_device_train_batch_size: 24
num_generations: 8
logging_steps: 1
bf16: True
gradient_checkpointing: True
log_completions: True
max_prompt_length: 2048
max_completion_length: 512
wandb_log_unique_prompts: True
# beta: 0.1
epsilon_high: 0.28
save_steps: 100
use_vllm: True
vllm_update_steps: 10
vllm_server_host: ${RCALL_JOB_NAME}-1
# vllm_server_port: 26500

