# model_name_or_path: az://orngcresco/data/boren/data/ckp/phi4_mm_bias
# model_name_or_path: /home/boren/data/ckp/hf_models/phi4_mm_bias
model_name_or_path: /home/boren/data/ckp/hf_models/Phi-4-multimodal-instruct
new_run: True
reward_funcs: [reward_full_error]
reward_func_kwargs:
    tn: simple
    unit: char
report_to: [] # no wandb
learning_rate: 1e-5
save_only_model: True
save_total_limit: 5
save_on_each_node: True
# new_lora: True
# lr_scheduler_type: cosine
output_dir: ~/outputs/debug
per_device_train_batch_samples: 2
num_generations: 5
generation_scale: 2
token_entropy_percentile_threshold: 0.8
# dataloader_drop_last: True

scale_rewards: False
temperature: 1.1
logging_steps: 1
bf16: True
gradient_checkpointing: True
gradient_accumulation_steps: 2
# steps_per_generation: 2
log_completions: True
max_prompt_length: 6000
max_completion_length: 512
inject_reference: True
#
# beta: 0.1
epsilon_high: 0.28
save_steps: 100
use_vllm: True
vllm_mode: colocate
vllm_tensor_parallel_size: 1
vllm_gpu_memory_utilization: 0.35
vllm_imp_ratio_cap: 5
# use_vllm_lora_update: True # not work yet
# vllm_server_host: ${VLLM_SERVER_HOST}
# vllm_server_host: 10.133.219.39
# vllm_server_port: 26500

train_data:
    dataset_name: chunk
    # streaming: True
    max_chunks: 2
    max_egs: 30

    specs:
        - manifest_file: /datablob1/users/xioxiao/am_data/en_long/ami_ihm_mix_profiles_v2/train_dev/chunks/chunk_b7a4d20c-7283-11f0-9682-b04f13015df5.json
          chunk_path: /datablob1/users/xioxiao/am_data/en_long/ami_ihm_mix_profiles_v2/train_dev/chunks/

    diarization:
        trans_key: text
# eval_strategy: steps
# eval_on_start: True
# eval_steps: 10
# per_device_eval_batch_size: 20
# num_eval_generations: 2
# eval_data:
#     - nickname: clean_no
#       dataset_name: ls_bias
#       jsonl_path: /home/boren/data/librispeech_biasing/ref/test-clean.biasing_100.jsonl
#       data_dir: az://orngscuscresco/data/boren/data
#   bias_key: null # null
# data_dir: az://${DATA_STORAGE}/data/boren/data
# - nickname: other_no
#   dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-other.biasing_100.jsonl
#   data_dir: az://orngscuscresco/data/boren/data
#   bias_key: null # distractors
# data_dir: az://${DATA_STORAGE}/data/boren/data
# - nickname: clean_100
# dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-clean.biasing_100.jsonl
#   bias_key: distractors # distractors
#   # data_dir: az://${DATA_STORAGE}/data/boren/data
#   data_dir: az://orngscuscresco/data/boren/data
# - nickname: other_100
# dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-other.biasing_100.jsonl
#   bias_key: distractors # distractors
#   # data_dir: az://${DATA_STORAGE}/data/boren/data
#   data_dir: az://orngscuscresco/data/boren/data
# - nickname: clean_500
# dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-clean.biasing_500.jsonl
#   bias_key: distractors # distractors
#   # data_dir: az://${DATA_STORAGE}/data/boren/data
#   data_dir: az://orngscuscresco/data/boren/data
# - nickname: other_500
# dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-other.biasing_500.jsonl
#   bias_key: distractors # distractors
#   # data_dir: az://${DATA_STORAGE}/data/boren/data
#   data_dir: az://orngscuscresco/data/boren/data
# - nickname: clean_1000
# dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-clean.biasing_1000.jsonl
#   bias_key: distractors # distractors
#   # data_dir: az://${DATA_STORAGE}/data/boren/data
#   data_dir: az://orngscuscresco/data/boren/data
# - nickname: other_1000
# dataset_name: ls_bias
#   jsonl_path: /home/boren/data/LibriSpeech_biasing/ref/test-other.biasing_1000.jsonl
#   bias_key: distractors # distractors
#   # data_dir: az://${DATA_STORAGE}/data/boren/data
#   data_dir: az://orngscuscresco/data/boren/data
