use_vllm: true
vllm_max_length: 10240 # default 1024*10 #10k
batch_size: 512
generation_config:
  max_new_tokens: 1024
  do_sample: false
# model_path: /root/data/ckp/hf_models/phi4_mm_bias
# model_path: /root/data/ckp/hf_models/Phi-4-multimodal-instruct
model_path: /root/data/ckp/hf_models/Phi-4-multimodal-instruct
eval_data:
  - nickname: ls_train_960hr_biasing_smp_v2_sc3k
    dataset_name: tsv
    #   num_egs: 5000
    #   load_audio: True
    #   streaming: True
    # tsv_paths: az://orngwus2cresco/data/boren/data/LibriSpeech/debug.tsv
    tsv_paths: az://${DATA_STORAGE}/data/boren/data/LibriSpeech/asr_train_transcribe.tsv
    biasing:
      buffer_size: 100000
      max_piece_len: 1
      bias_prob: 1
      hit_prob: 1
      miss_prob: 1
      context_prob: 0.8 # prob for context
      sample_range: [0, 1000] # all rare words
      sampling_version: v2
      hit_ratio: [0.9, 1.0]
      log_interval: 10000 # print biasing every 10000 samples
      common_word_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_words.count.txt
      common_word_num: 3000
