use_vllm: true
vllm_max_length: 8192 # limited by 7B model
batch_size: 128
generation_config:
  max_new_tokens: 1024
  do_sample: false

max_chunk_len: 30
# with_history: True
# model_path: /root/data/ckp/hf_models/phi4_mm_bias
#
# model_path: /root/data/ckp/hf_models/Phi-4-multimodal-instruct
model_path: /root/data/ckp/hf_models/phi4_mm_bias
eval_data:
  - nickname: entity_Conversation_Gaming
    dataset_name: inhouse_entity
    data_dir: /root/data/
    jsonl_path: /root/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Gaming_Entity_FY24Q1_en-US_DTEST/test.jsonl
    bias_file: /root/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 500

  - nickname: entity_Conversation_Insurance
    dataset_name: inhouse_entity
    data_dir: /root/data/
    jsonl_path: /root/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Insurance_Entity_FY24Q1_en-US_DTEST/test.jsonl
    bias_file: /root/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 500

  - nickname: entity_Conversation_K12HigherEdu
    dataset_name: inhouse_entity
    data_dir: /root/data/
    jsonl_path: /root/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_K12HigherEdu_Entity_FY24Q4_en-US_DTEST_OfflineDataCollection/test.jsonl
    bias_file: /root/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 500

  - nickname: entity_Conversation_Retail
    dataset_name: inhouse_entity
    data_dir: /root/data/
    jsonl_path: /root/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Retail_Entity_FY24Q4_en-US_DTEST_OfflineDataCollection/test.jsonl
    bias_file: /root/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 500

  - nickname: entity_Conversation_ScienceTech
    dataset_name: inhouse_entity
    data_dir: /root/data/
    jsonl_path: /root/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_ScienceTech_Entity_FY24Q1_en-US_DTEST/test.jsonl
    bias_file: /root/data/librispeech_biasing/words/all_rare_words.txt
    max_bias: 500
