use_vllm: True
vllm_max_length: 8192
batch_size: 32
generation_config:
  max_new_tokens: 512
  # temperature: 0.0
  do_sample: false
new_run: True
max_chunk_len: 30
# with_history: True
# model_path: /root/data/ckp/hf_models/phi4_mm_bias
# model_path: /root/outputs/dev-n2-hpe5/grpo_vllm_libri_v1_n12_err_m1000_p8_bp8_mp1_all_sc1k_seed_rw10_coloc/checkpoint-8400/
# model_path: /root/data/ckp/hf_models/phi4_mm_bias
model_path: /home/boren/data/ckp/hf_models/Phi-4-multimodal-instruct
# model_path: /home/boren/data/ckp/hf_models/Phi4-7b-ASR-2506 # a lora merged model
# model_with_lora: False
# model_path: /home/boren/data/ckp/hf_models/Phi4-7b-ASR-2506-v2
# model_path: /home/boren/data/ckp/hf_models/Phi-4-7b-ASR-merged # a lora merged model
eval_data:
  - nickname: ls_train_debug_biasing_smp2
    dataset_name: tsv
    num_egs: 2
    #   load_audio: True
    #   streaming: True
    tsv_paths: /home/boren/data/LibriSpeech/debug.tsv
    biasing:
      buffer_size: 100000
      max_piece_len: 1
      bias_prob: 1
      hit_prob: 1
      miss_prob: 1
      context_prob: 0.8 # prob for context
      sample_range: [0, 1000] # all rare words
      sampling_version: v2
      hit_ratio: [0.9, 1.0]
      log_interval: 10000 # print biasing every 10000 samples
      # common_word_file: az://${DATA_STORAGE}/data/boren/data/librispeech_biasing/words/all_words.count.txt
      # common_word_num: 3000
    # tsv_paths: az://${DATA_STORAGE}/data/boren/data/LibriSpeech/asr_train_transcribe.tsv
# eval_data:
#   # - nickname: health
#   #   num_egs: 2
#   #   dataset_name: inhouse_entity
#   #   jsonl_path: /datablob1/users/ruchaofan/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_DeliciousHealthy_Entity_FY24Q1_en-US_DTEST/test.jsonl
#   #   distractor_file: /home/boren/data/librispeech_biasing/words/all_rare_words.txt
#   #   max_bias: 100

#   - nickname: entity_Conversation_Gaming_0
#     dataset_name: inhouse_entity
#     data_dir: /home/boren/data/
#     src_dir: /home/boren/data/
#     jsonl_path: /home/boren/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_Gaming_Entity_FY24Q1_en-US_DTEST/segments.jsonl
#     distractor_file: /home/boren/data/librispeech_biasing/words/all_rare_words.txt
#     max_bias: 0
# jsonl_path: /root/data/Evaluation/InhouseASR/EWER/en-US-entity-v3/Conversation_DomainSet_DTEST_DeliciousHealthy_Entity_FY24Q1_en-US_DTEST/test.jsonl
# data_dir: /root/data/
# - nickname: clean_no
#   num_egs: 20
#   dataset_name: ls_bias
#   jsonl_path: /home/boren/data/librispeech_biasing/ref/test-clean.biasing_100.jsonl
# jsonl_path: /root/data/librispeech_biasing/ref/test-clean.biasing_100.jsonl
# data_dir: /root/data/

# bias_key: distractors
# - nickname: clean_1000
#   num_egs: 512
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-clean.biasing_1000.jsonl
#   bias_key: distractors
# - nickname: other_no
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-other.biasing_100.jsonl
# - nickname: clean_100
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-clean.biasing_100.jsonl
#   bias_key: distractors
# - nickname: other_100
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-other.biasing_100.jsonl
#   bias_key: distractors
# - nickname: clean_500
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-clean.biasing_500.jsonl
#   bias_key: distractors
# - nickname: other_500
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-other.biasing_500.jsonl
#   bias_key: distractors
# - nickname: other_1000
#   dataset_name: ls_bias
#   jsonl_path: /root/data/librispeech_biasing/ref/test-other.biasing_1000.jsonl
#   bias_key: distractors
